version: "3"
services:
  gitea:
    image: gitea/gitea:1.19.0-rootless
    container_name: gitea
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000    
    ports:
      - 3000:3000
      - 2222:2222
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
