version: "3"
services:
  avahi2dns:
    network_mode: host
    build:
      context: avahi2dns
      args:
        PUID: 1000
        PGID: 1000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    ports:
     - 5454:5454

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000    
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp
      # DNS-over-QUIC
      - 784:784/udp
      # HTTPS/DNS-over-HTTPS
      # - 443:443/tcp
      # DNS-over-TLS
      - 853:853/tcp
      # WebUI
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
      # DNSCrypt
      # - 5443:5443/tcp
      # - 5443:5443/udp
      # DHCP server
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: unless-stopped
