---
version: "3"
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: docker.home
    environment:
      DISABLE_TELEMETRY: 1
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/host/etc/os-release:ro
      - ./netdatacache:/var/cache/netdata
      - ./netdatalib:/var/lib/netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
