version: '3'
services:
  db:
    # database with mariadb
    image: mariadb:10.11
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    tmpfs:
      - /tmp
    environment:
      - TZ='America/New_York'
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mattermost
      - MYSQL_USER=mattermost
      - MYSQL_PASSWORD=mattermost
      # - PROXY=${http_proxy}
    volumes:
       - ./volumes/maria/data:/var/lib/mysql
       - ./volumes/srv:/srv
       - /etc/localtime:/etc/localtime:ro
    expose:
      - 3306

  app:
    build:
      context: app
      args:
        - edition=team
        - PUID=2000
        - PGID=2000
    depends_on:
    - db
    restart: unless-stopped
    volumes:
      - ./volumes/mm/config:/mattermost/config:rw
      - ./volumes/mm/data:/mattermost/data:rw
      - ./volumes/mm/logs:/mattermost/logs:rw
      - ./volumes/srv:/srv
      - /etc/localtime:/etc/localtime:ro
    ports:
     - "8065:8065"
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mattermost
      - MM_PASSWORD=mattermost
      - MM_DBNAME=mattermost
      - DB_HOST=db
      - DB_PORT_NUMBER=3306
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=mattermost:mattermost@tcp(db:3306)/mattermost?charset=utf8mb4,utf8
