---
version: '3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome:stable
    volumes:
      - ./config:/config
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
